apiVersion: apps/v1
kind: Deployment
metadata:
  name: magicbackend-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: magicbackend-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: magicbackend-ui
    spec:
      containers:
        - name: frontend
          image: registry.digitalocean.com/magicbackend/magicbackend-ui:latest
---
kind: Service
apiVersion: v1
metadata:
  name: magicbackend-ui
spec:
  selector:
    app.kubernetes.io/name: magicbackend-ui
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
